/** Shared inline styles — dark ZorvoIQ shell, no extra CSS deps */
export const fs = {
  sectionTitle: {
    margin: '0 0 12px',
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: '0.2em',
    textTransform: 'uppercase' as const,
    color: '#94a3b8',
  },
  label: {
    display: 'block',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    color: '#94a3b8',
    marginBottom: 8,
  },
  box: {
    background: '#0f150f',
    borderRadius: 16,
    border: '1px solid #1f2e1f',
    padding: 16,
  },
  input: {
    width: '100%',
    minHeight: 48,
    padding: '14px 16px',
    background: '#111810',
    border: '1px solid #1f2e1f',
    borderRadius: 12,
    color: '#f1f5f9',
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  select: {
    width: '100%',
    minHeight: 48,
    padding: '14px 16px',
    background: '#111810',
    border: '1px solid #1f2e1f',
    borderRadius: 12,
    color: '#f1f5f9',
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  toggleOn: {
    width: '100%',
    minHeight: 48,
    padding: '14px 16px',
    borderRadius: 16,
    border: '1px solid #3ddb6f',
    background: '#3ddb6f',
    color: '#000',
    fontWeight: 900,
    fontSize: 11,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    textAlign: 'left' as const,
  },
  toggleOff: {
    width: '100%',
    minHeight: 48,
    padding: '14px 16px',
    borderRadius: 16,
    border: '1px solid #1f2e1f',
    background: '#0f150f',
    color: '#cbd5e1',
    fontWeight: 900,
    fontSize: 11,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    textAlign: 'left' as const,
  },
  dimGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 },
};
